name: Check links for modified files

on:
  push:
    branches:
      - master
      - issue-*
  schedule:
    - cron: "0 1 * * 1"


permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write


jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        folder-path: './'
        file-path: './readme.md'